import { Unit } from '@models/unit.model';

export const mockUnits: Unit[] = [
  {
    id: 1,
    name: 'Archer',
    description: 'Ranged unit with high attack speed.',
    age: 'Feudal',
    cost: { Food: 50, Wood: 0, Gold: 10 },
    build_time: 30,
    reload_time: 2,
    hit_points: 40,
    attack: 4,
    accuracy: '80%',
    expansion: '',
    attack_delay: 0,
    movement_rate: 0,
    line_of_sight: 0,
    range: 0,
    armor: '',
    attack_bonus: [],
    armor_bonus: [],
    search_radius: 0,
  },
  {
    id: 2,
    name: 'Knight',
    description: 'Strong melee unit.',
    age: 'Castle',
    cost: { Food: 60, Wood: 0, Gold: 75 },
    build_time: 40,
    reload_time: 0,
    hit_points: 100,
    attack: 8,
    accuracy: '75%',
    expansion: '',
    attack_delay: 0,
    movement_rate: 0,
    line_of_sight: 0,
    range: 0,
    armor: '',
    attack_bonus: [],
    armor_bonus: [],
    search_radius: 0,
  },
];
